config/routes.rb
Rails.application.routes.draw do
  resources :quotations do
    member do
      get 'get_payment'
    end
  end
  get 'get_rates', to: 'quotations#get_rates'
  get 'get_banks', to: 'quotations#get_banks'
  resources :banks
  resources :rates
  resources :workers
  root 'home#index'
  # Go to registrations_controller for details
  devise_for :users, controllers: {sessions: "sessions",registrations: "registrations", passwords: "passwords"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bank.rb
class Bank < ApplicationRecord
    validates :name,:headline, presence: true
    validates :status, inclusion: { in: [true,false]}
    
    validate :bank_exist

    def bank_exist
	    if not self.name.nil?
	      banks = ['Banesco','Banco de Venezuela', 'BBVA Provincial', 'Mercantil',
	      'Banco Occidental de Descuento','Banco Bicentenario', 
	      'Banco Nacional de Crédito', 'Banco del Tesoro', 'Bancaribe', 
	      'Banco Exterior', 'Banco Fondo Común', 'Banco Venezolano de Crédito',
	      'Banco Sofitasa', 'Banplus', 'Bancrecer', 'Banco Plaza', 'Banco Caroní',
	      'Banco Activo', 'Banco de Comercio Exterior', 'DELSUR', 'Banfanb', '100% Banco',
	      'Banco Agrícola de Venezuela', 'Bancamiga', 'Instituto Municipal de Crédito Popular',
	      'Citibank Sucursal Venezuela', 'Mi Banco', 'Bangente', 
	      'Banco de Exportación y Comercio', 'Banco Internacional de Desarrollo']

	      if not banks.include?(self.name)
	        errors.add(:bank, "El banco seleccionado no esta registrado en nuestras plataformas")
	      end   
	    end
  	end

end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]
  before_action :ony_worker, only: [:show, :edit, :destroy, :new, :index, :update, :create]
  before_action :only_admin, only: [:edit, :destroy, :new, :update, :create]
  # GET /banks
  # GET /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1
  # GET /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
    @banks_ = ['Banesco','Banco de Venezuela', 'BBVA Provincial', 'Mercantil',
      'Banco Occidental de Descuento','Banco Bicentenario', 
      'Banco Nacional de Crédito', 'Banco del Tesoro', 'Bancaribe', 
      'Banco Exterior', 'Banco Fondo Común', 'Banco Venezolano de Crédito',
      'Banco Sofitasa', 'Banplus', 'Bancrecer', 'Banco Plaza', 'Banco Caroní',
      'Banco Activo', 'Banco de Comercio Exterior', 'DELSUR', 'Banfanb', '100% Banco',
      'Banco Agrícola de Venezuela', 'Bancamiga', 'Instituto Municipal de Crédito Popular',
      'Citibank Sucursal Venezuela', 'Mi Banco', 'Bangente', 
      'Banco de Exportación y Comercio', 'Banco Internacional de Desarrollo']
  end

  # GET /banks/1/edit
  def edit
    @banks_ = ['Banesco','Banco de Venezuela', 'BBVA Provincial', 'Mercantil',
      'Banco Occidental de Descuento','Banco Bicentenario', 
      'Banco Nacional de Crédito', 'Banco del Tesoro', 'Bancaribe', 
      'Banco Exterior', 'Banco Fondo Común', 'Banco Venezolano de Crédito',
      'Banco Sofitasa', 'Banplus', 'Bancrecer', 'Banco Plaza', 'Banco Caroní',
      'Banco Activo', 'Banco de Comercio Exterior', 'DELSUR', 'Banfanb', '100% Banco',
      'Banco Agrícola de Venezuela', 'Bancamiga', 'Instituto Municipal de Crédito Popular',
      'Citibank Sucursal Venezuela', 'Mi Banco', 'Bangente', 
      'Banco de Exportación y Comercio', 'Banco Internacional de Desarrollo']
  end

  # POST /banks
  # POST /banks.json
  def create
    @bank = Bank.new(bank_params)
    @banks_ = ['Banesco','Banco de Venezuela', 'BBVA Provincial', 'Mercantil',
      'Banco Occidental de Descuento','Banco Bicentenario', 
      'Banco Nacional de Crédito', 'Banco del Tesoro', 'Bancaribe', 
      'Banco Exterior', 'Banco Fondo Común', 'Banco Venezolano de Crédito',
      'Banco Sofitasa', 'Banplus', 'Bancrecer', 'Banco Plaza', 'Banco Caroní',
      'Banco Activo', 'Banco de Comercio Exterior', 'DELSUR', 'Banfanb', '100% Banco',
      'Banco Agrícola de Venezuela', 'Bancamiga', 'Instituto Municipal de Crédito Popular',
      'Citibank Sucursal Venezuela', 'Mi Banco', 'Bangente', 
      'Banco de Exportación y Comercio', 'Banco Internacional de Desarrollo']
    
    respond_to do |format|
      if @bank.save
        format.html { redirect_to @bank, notice: 'Banco fue creado con éxito.' }
        format.json { render :show, status: :created, location: @bank }
      else
        format.html { render :new }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1
  # PATCH/PUT /banks/1.json
  def update
    @banks_ = ['Banesco','Banco de Venezuela', 'BBVA Provincial', 'Mercantil',
      'Banco Occidental de Descuento','Banco Bicentenario', 
      'Banco Nacional de Crédito', 'Banco del Tesoro', 'Bancaribe', 
      'Banco Exterior', 'Banco Fondo Común', 'Banco Venezolano de Crédito',
      'Banco Sofitasa', 'Banplus', 'Bancrecer', 'Banco Plaza', 'Banco Caroní',
      'Banco Activo', 'Banco de Comercio Exterior', 'DELSUR', 'Banfanb', '100% Banco',
      'Banco Agrícola de Venezuela', 'Bancamiga', 'Instituto Municipal de Crédito Popular',
      'Citibank Sucursal Venezuela', 'Mi Banco', 'Bangente', 
      'Banco de Exportación y Comercio', 'Banco Internacional de Desarrollo']
      
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to @bank, notice: 'Banco fue actualizado con éxito.' }
        format.json { render :show, status: :ok, location: @bank }
      else
        format.html { render :edit }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1
  # DELETE /banks/1.json
  def destroy
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to banks_url, notice: 'Banco fue eliminado con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    def ony_worker
      if not current_user.nil?
        if current_user.type_person == 'normal'
          redirect_to root_path, notice: "No tienes permiso para acceder a esta sección, debes ser un trabajador", status: :unauthorized
        end
      else
        redirect_to new_user_session_path, notice: "Debes iniciar sesion para acceder", status: :unauthorized
      end
    end

    def only_admin
      if not current_user.nil?
        if current_user.type_person == 'worker'
          redirect_to banks_path, notice: "No tienes permiso para acceder a esta sección, debes ser administrador", status: :unauthorized
        end
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.require(:bank).permit(:name, :headline, :status)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_form.html.erb
<%= form_with(model: bank, local: true) do |form| %>
  <% if bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
      <% bank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :headline %>
    <%= form.text_field :headline %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<div class="testing">
  <div class="wrapper ">
    <%= render 'partials/sidebar', report: false, worker: false, bank: true, rate: false %>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          <!-- your content here -->
          <div class="navDashContent">
            <div class="titleDashContent">
              <h2>Bancos <br>
              <div class="line"></div></h2>
            </div>
          </div>
          <div class="Dashcontent">
            <%= form_with(model: @bank, local: true) do |form| %>
              <% if @bank.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@bank.errors.count, "error") %> Se ha prohibido la creación del banco debiado a:</h2>
                  <ul>
                    <% @bank.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="row">
                <div class="input-field col s12 l6">
                    <p style="font-weight:bold">Nombre del Banco <span style="color: red">*</span>  </p>
                    <%= form.select :name, @banks_.collect{|u| [u, u]},{:include_blank => "Seleccione un banco"}, id: 'banks',class: 'validate', required: true%>
                </div>
                <div class="input-field col s12 l6">
                  <p style="font-weight:bold">Nombre del Titular <span style="color: red">*</span>  </p>
                  <%= form.text_field :headline, id: 'first_name', class: 'validate', required: true %>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12 l6">
                <p style="font-weight:bold"> Estatus  <span style="color: red">*</span>  </p>
                  <%= form.select(:status, options_for_select([['Activo', 1], ['Inactivo', 0]], @bank.status ? 1 : 0 )) %>
                </div>
                <div class="input-field col s12 l6">
                </div>
              </div>        
              <div class="input-field col s12">
                <%= link_to 'VOLVER', banks_path, class:"waves-effect waves-light btn btn-theme" %>
                <%= form.submit 'GUARDAR', class:"waves-effect waves-light btn btn-theme" %>
              </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/banks/index.html.erb
<div class="testing">
  <div class="wrapper ">
    <%= render 'partials/sidebar', report: false, worker: false, bank: true, rate: false %>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          <p id="notice"><%= notice %></p>
          <!-- your content here -->
          <div class="navDashContent">
            <div class="titleDashContent">
              <h2>Bancos <br>
                <div class="line"></div>
              </h2>
            </div>
            <% if current_user.type_person == 'admin' %>
       			  <td><%= link_to 'CREAR', new_bank_path, class:'waves-effect waves-light btn btn-theme' %></td>
            <%end%>
          </div>
          <div class="Dashcontent">
            <div class="table-responsive">             
              <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Nombre del Banco</th>
                  <th>Titular de la cuenta</th>
                  <th>Estatus</th>
                  <th></th>
                  <% if current_user.type_person == 'admin' %>
                    <th></th>
                    <th></th>
                  <%end%>
                </tr>
              </thead>
              <tbody>
                <% @banks.each do |bank| %>
                  <tr>
                    <td><%= bank.name %></td>
                    <td><%= bank.headline %></td>
                    <td class="<%= bank.status ? 'status-green' : 'red-text' %>" style="font-weight: bold;"><%= bank.status ? 'Activo' : 'Inactivo' %></td>
                    <td><%= link_to 'MOSTRAR', bank, class:'waves-effect waves-light btn btn-theme' %></td>
                    <% if current_user.type_person == 'admin' %>
                      <td><%= link_to 'MODIFICAR', edit_bank_path(bank) , class:'waves-effect waves-light btn btn-theme' %></td>
                      <td><%= link_to 'ELIMINAR', bank, method: :delete, data: { confirm: '
                        ¿Está seguro que desea elimnar el banco?' }, class:'waves-effect waves-light btn btn-theme' %></td>
                    <%end%>
                  </tr>
                <%end%>
              </tbody>
            </table>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/banks/new.html.erb
<div class="testing">
  <div class="wrapper ">
    <%= render 'partials/sidebar', report: false, worker: false, bank: true, rate: false %>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
          
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
        
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          <!-- your content here -->
          <div class="navDashContent">
            <div class="titleDashContent">
              <h2>Bancos <br>
              <div class="line"></div></h2>
            </div>
          </div>
          <div class="Dashcontent">
            <%= form_with(model: @bank, local: true) do |form| %>
              <% if @bank.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@bank.errors.count, "error") %> Se ha prohibido la creación del banco debiado a:</h2>
                  <ul>
                    <% @bank.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="row">
                <div class="input-field col s12 l6">
                    <p>Nombre del Banco</p>
                    <%= form.select :name, @banks_.collect{|u| [u, u]},{:include_blank => "Seleccione un banco"}, id: 'banks',class: 'validate', required: true%>
                </div>
                <div class="input-field col s12 l6">
                  <p>Nombre del Titular</p>
                  <%= form.text_field :headline, id: 'first_name', class: 'validate', required: true %>
                </div>
              </div>        
              <div class="input-field col s12">
                <%= link_to 'VOLVER', banks_path, class:"waves-effect waves-light btn btn-theme" %>
                <%= form.submit 'CREAR', class:"waves-effect waves-light btn btn-theme" %>
              </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/banks/show.html.erb
<div class="testing">
  <div class="wrapper ">
    <%= render 'partials/sidebar', report: false, worker: false, bank: true, rate: false %>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          <p id="notice"><%= notice %></p>
          <!-- your content here -->
          <div class="navDashContent">
            <div class="titleDashContent">
              <h2>Bancos <br>
              <div class="line"></div></h2>
            </div>
          </div>
          <div class="Dashcontent">
            <div class="row">
              <div class="input-field col s12 l6">
                <p>Nombre del Banco</p>
                <input id="first_name" type="text" class="validate" value="<%= @bank.name %>" disabled>
              </div>
              <div class="input-field col s12 l6">
                <p>Nombre de Beneficiario</p>
                <input id="first_name" type="text" class="validate" value="<%= @bank.headline %>" disabled>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12 l6">
                <p>Estado</p>
                <input id="first_name" type="text" class="validate" value="<%= @bank.status ? 'Activo' : 'Inactivo' %>" disabled>
              </div>
              <div class="input-field col s12 l6">
              </div>
            </div>
            <div class="input-field col s12">
              <%= link_to 'VOLVER', banks_path, class:"waves-effect waves-light btn btn-theme" %>
              <% if current_user.type_person == 'admin' %>
                <%= link_to 'EDITAR', edit_bank_path(@bank), class:"waves-effect waves-light btn btn-theme" %>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>