config/routes.rb
Rails.application.routes.draw do
  resources :quotations do
    member do
      get 'get_payment'
    end
  end
  get 'get_rates', to: 'quotations#get_rates'
  get 'get_banks', to: 'quotations#get_banks'
  resources :banks
  resources :rates
  resources :workers
  root 'home#index'
  # Go to registrations_controller for details
  devise_for :users, controllers: {sessions: "sessions",registrations: "registrations", passwords: "passwords"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]
  before_action :ony_worker, only: [:show, :edit, :destroy, :new, :index, :update, :create]
  before_action :only_admin, only: [:edit, :destroy, :new, :update, :create, :index, :show]

  def index
    @users = User.where.not(type_person: 'normal')
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(worker_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to worker_path(@user), notice: 'El trabajador fue creada exitosamente.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(worker_params)
        format.html { redirect_to worker_path(@user), notice: 'El trabajador fue actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to workers_path, notice: 'El trabajador fue eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    def ony_worker
      if not current_user.nil?
        if current_user.type_person == 'normal'
          redirect_to root_path, notice: "No tienes permiso para acceder a esta sección, debes ser un trabajador", status: :unauthorized
        end
      else
        redirect_to new_user_session_path, notice: "Debes iniciar sesion para acceder", status: :unauthorized
      end
    end

    def only_admin
      if not current_user.nil?
        if current_user.type_person == 'worker'
          redirect_to workers_path, notice: "No tienes permiso para acceder a esta sección, debes ser administrador", status: :unauthorized
        end
      end
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:user).permit(:email, :name, :password, :phone, :status, :type_person)
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/edit.html.erb
<div class="testing">
  <div class="wrapper ">
   <%= render 'partials/sidebar', report: false, worker: true, bank: false, rate: false %>
   <div class="main-panel">
     <!-- Navbar -->
     <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper"></div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
        </div>
      </nav>
     <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
         <!-- your content here -->
          <div class="titleDashContent">
            <h2>
              Trabajadores <br>
              <div class="line"></div>
            </h2>
          </div>
          <div class="Dashcontent">
            <%= form_for @user, :url => worker_path(@user), :method => :put do |form| %>
              <% if @user.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@user.errors.count, "error") %> Se ha prohibido la creación del trabajador por:</h2>
                  <ul>
                  <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="row">
                <div class="input-field col s12 l6">
                  <p>Nombre</p>
                  <%= form.text_field :name, autofocus: true, autocomplete: "nombre", class: 'validate', id:'first_name' %>
                </div>
                <div class="input-field col s12 l6">
                  <p>Correo</p>
                  <%= form.email_field :email, autocomplete: "email", class: 'validate', id:'first_name' %>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12 l6">
                  <p>Tipo de trabajador</p>
                  <%= form.select :type_person, options_for_select([['Administrador', 'admin'], ['Trabajador', 'worker'], ['Persona Normal', 'normal']], @user.type_person) %>
                </div>
                <div class="input-field col s12 l6">
                  <p>Teléfono</p>
                  <%= form.telephone_field :phone, autocomplete: "teléfono", class: 'validate', id:'first_name', placeholder: "+584140710854" %>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <%= link_to 'VOLVER', workers_path, class:'waves-effect waves-light btn btn-theme' %>
                  <%= form.submit 'GUARDAR', class:'waves-effect waves-light btn btn-theme' %>     
                </div>
              </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/workers/index.html.erb
<div class="testing" >
	<div class="wrapper ">
    <%= render 'partials/sidebar', report: false, worker: true, bank: false, rate: false %>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper"></div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          <p id="notice"><%= notice %></p>
          <!-- your content here -->
          <div class="navDashContent">
            <div class="titleDashContent">
              <h2>Trabajadores <br>
              <div class="line"></div></h2>
            </div>
       			<td><%= link_to 'CREAR', new_worker_path, class:'waves-effect waves-light btn btn-theme' %></td>
          </div>
          <div class="Dashcontent">
            <div class="table-responsive">             
              <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Nombre Completo</th>
                  <th>Email</th>
                  <th>Teléfono</th>
                  <th>Tipo</th>
                  <th></th>
                  <th></th>
                  <% if current_user.type_person == 'admin' %>
                    <th></th>
                  <%end%>
                </tr>
              </thead>
              <tbody>
                <% @users.each do |user| %>
                  <tr>
                    <td><%= user.name %></td>
                    <td><%= user.email %></td>
                    <td><%= user.phone %></td>
                    <% if user.type_person == 'admin' %>
                      <td>Administrador</td>
                    <% elsif user.type_person == 'worker'%>
                      <td>Trabajador</td>
                    <%end%>
                    <td>     
                      <%= link_to 'MOSTRAR', worker_path(user), class:'waves-effect waves-light btn btn-theme' %>
                    </td> 
                    <td>        
                      <%= link_to 'MODIFICAR', edit_worker_path(user), class:'waves-effect waves-light btn btn-theme' %>
                    </td>
                    <td><%= link_to 'ELIMINAR', worker_path(user), method: :delete, data: { confirm: '¿Seguro que desea eliminar el trabajador?' }, class:'waves-effect waves-light btn btn-theme' %></td>
                  </tr>
                <%end%>
              </tbody>
            </table>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/workers/new.html.erb
<div class="testing">
    <div class="wrapper ">
      <%= render 'partials/sidebar', report: false, worker: true, bank: false, rate: false %>
      <div class="main-panel">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
          <div class="container-fluid">
            <div class="navbar-wrapper"></div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
              <span class="sr-only">Toggle navigation</span>
              <span class="navbar-toggler-icon icon-bar"></span>
              <span class="navbar-toggler-icon icon-bar"></span>
              <span class="navbar-toggler-icon icon-bar"></span>
            </button>
          </div>
        </nav>
        <!-- End Navbar -->
        <div class="content">
          <div class="container-fluid">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
            <!-- your content here -->
            <div class="titleDashContent">
              <h2>Trabajadores <br>
              <div class="line"></div></h2>
            </div>
            <div class="Dashcontent">
              <%= form_for @user, :url => workers_path, :method => :post do |f| %>
                <% if @user.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@user.errors.count, "error") %> Se ha prohibido la creación del trabajador por:</h2>
                    <ul>
                    <% @user.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>
                <div class="row">
                  <div class="input-field col s12 l6">
                    <p>Nombre</p>
                    <%= f.text_field :name, autofocus: true, autocomplete: "nombre", class: 'validate', id:'first_name' %>
                  </div>
                  <div class="input-field col s12 l6">
                    <p>Correo</p>
                    <%= f.email_field :email, autocomplete: "email", class: 'validate', id:'first_name' %>
                  </div>
                </div>
                <div class="row">
                  <div class="input-field col s12 l6">
                    <p>Contraseña</p>
                    <%= f.password_field :password, autocomplete: "off", class: 'validate', id:'first_name' %>
                  </div>
                  <div class="input-field col s12 l6">
                    <p>Teléfono</p>
                    <%= f.telephone_field :phone, class: 'validate', id:'first_name', placeholder: "+584140710854" %>
                  </div>
                </div>
                <div class="row">
                  <div class="input-field col s6">
                    <p>Tipo de trabajador</p>
                    <%= f.select :type_person, options_for_select([['Administrador', 'admin'], ['Trabajador', 'worker'], ['Persona Normal', 'normal']]) %>
                  </div>
                  <div class="input-field col s12 l6">
                  </div>
                </div>
                <div class="row">
                  <div class="input-field col s12">
                    <%= link_to 'VOLVER', workers_path, class:'waves-effect waves-light btn btn-theme' %>
                    <%= f.submit 'CREAR', class:'waves-effect waves-light btn btn-theme' %>
                  </div>
                </div>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/workers/show.html.erb
<div class="testing">
  <div class="wrapper ">
   <%= render 'partials/sidebar', report: false, worker: true, bank: false, rate: false %>
   <div class="main-panel">
     <!-- Navbar -->
     <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
       <div class="container-fluid">
         <div class="navbar-wrapper"></div>
         <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
           <span class="sr-only">Toggle navigation</span>
           <span class="navbar-toggler-icon icon-bar"></span>
           <span class="navbar-toggler-icon icon-bar"></span>
           <span class="navbar-toggler-icon icon-bar"></span>
         </button>
       </div>
     </nav>
     <!-- End Navbar -->
     <div class="content">
       <div class="container-fluid">
         <!-- your content here -->
          <div class="titleDashContent">
            <h2>
              Trabajadores <br>
              <div class="line"></div>
            </h2>
          </div>
          <div class="Dashcontent">
            <div class="row">
              <div class="input-field col s12 l6">
                <p>Nombre</p>
                <input id="first_name" type="text" class="validate" value="<%= @user.name %>" disabled>
              </div>
              <div class="input-field col s12 l6">
                <p>Correo</p>
                <input id="first_name" type="text" class="validate" value="<%= @user.email %>" disabled>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s6">
                <p>Tipo de trabajador</p>
                <% if @user.type_person == 'admin' %>
                  <input id="first_name" type="text" class="validate" value="Administrador" disabled>
                <% elsif @user.type_person == 'worker'%>
                  <input id="first_name" type="text" class="validate" value="Trabajador" disabled>
                <%end%>
              </div>
              <div class="input-field col s12 l6">
                <p>Teléfono</p>
                <input id="first_name" type="text" class="validate" value="<%= @user.phone %>" disabled>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= link_to 'VOLVER', workers_path, class:'waves-effect waves-light btn btn-theme'  %>
              </div>
            </div>
         </div>
       </div>
     </div>
   </div>
  </div>
</div>