config/routes.rb
Rails.application.routes.draw do
  resources :quotations do
    member do
      get 'get_payment'
    end
  end
  get 'get_rates', to: 'quotations#get_rates'
  get 'get_banks', to: 'quotations#get_banks'
  resources :banks
  resources :rates
  resources :workers
  root 'home#index'
  # Go to registrations_controller for details
  devise_for :users, controllers: {sessions: "sessions",registrations: "registrations", passwords: "passwords"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rate.rb
class Rate < ApplicationRecord
    validates :country, :value,  presence: true
    validates :value, numericality: true, numericality: {greater_than: 0 }

    validate :country_exist

    def country_exist
    	if not self.country.nil?
            rate = Rate.where('lower(country) = ?', self.country.downcase).first
    		if not rate.nil?
                if (not self.id.nil?) && rate.id != self.id
                    errors.add(:rate, "El pais modificado ya se encuentra registrado") 
                end
                if self.id.nil?
                    errors.add(:rate, "El pais seleccionado ya se encuentra registrado") 
                end    
    			
    		end	
    	end
    end


end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :set_rate, only: [:show, :edit, :update, :destroy]
  before_action :ony_worker, only: [:show, :edit, :destroy, :new, :index, :update, :create]
  before_action :only_admin, only: [:edit, :destroy, :new, :update, :create]

  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(rate_params)

    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: 'La tasa fue creada exitosamente.' }
        format.json { render :show, status: :created, location: @rate }
      else
        format.html { render :new }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1
  # PATCH/PUT /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to @rate, notice: 'La tasa fue actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @rate }
      else
        format.html { render :edit }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate.destroy
    respond_to do |format|
      format.html { redirect_to rates_url, notice: 'La tasa fue eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    def ony_worker
      if not current_user.nil?
        if current_user.type_person == 'normal'
          redirect_to root_path, notice: "No tienes permiso para acceder a esta sección, debes ser un trabajador", status: :unauthorized
        end
      else
        redirect_to new_user_session_path, notice: "Debes iniciar sesion para acceder", status: :unauthorized
      end
    end

    def only_admin
      if not current_user.nil?
        if current_user.type_person == 'worker'
          redirect_to rates_path, notice: "No tienes permiso para acceder a esta sección, debes ser administrador", status: :unauthorized
        end
      end
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rate_params
      params.require(:rate).permit(:country, :value)
    end
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/rates/_form.html.erb
<%= form_with(model: rate, local: true) do |form| %>
  <% if rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
      <% rate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rates/edit.html.erb
<div class="testing">
  <div class="wrapper ">
    <%= render 'partials/sidebar', report: false, worker: false, bank: false, rate: true %>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper"></div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          <!-- your content here -->
          <div class="titleDashContent">
            <h2>Tasa<br>
            <div class="line"></div></h2>
          </div>
          <div class="Dashcontent">
            <%= form_with(model: @rate, local: true) do |form| %>
              <% if @rate.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@rate.errors.count, "error") %> Se ha prohibido la creación de la tasa por:</h2>
                  <ul>
                    <% @rate.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="row">
                <div class="input-field col s12 l6">
                <p style="font-weight:bold">País<span style="color: red">*</span>  </p>
                  <%= form.text_field :country, id: 'first_name', class: 'validate' %>
                </div>
                <div class="input-field col s12 l6">
                <p style="font-weight:bold">Valor<span style="color: red">*</span>  </p>
                  <%= form.text_field :value, id: 'first_name', class: 'validate' %>
                </div>
              </div>
              <div class="input-field col s12">
                <%= link_to 'VOLVER', rates_path, class: "waves-effect waves-light btn btn-theme" %>
                <%= form.submit 'GUARDAR', class: "waves-effect waves-light btn btn-theme" %>
              </div>
            <% end %>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rates/index.html.erb
<div class="testing"> 
	<div class="wrapper ">
    <%= render 'partials/sidebar', report: false, worker: false, bank: false, rate: true %>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          <!-- your content here -->
          <p id="notice"><%= notice %></p>
          <div class="navDashContent">
            <div class="titleDashContent">
              <h2>
                Tasa<br>
                <div class="line"></div>
              </h2>
            </div>
            <% if current_user.type_person == 'admin' %>
       			  <td><%= link_to 'CREAR', new_rate_path, class:'waves-effect waves-light btn btn-theme' %></td>
            <%end%>
          </div>
          <div class="Dashcontent">
            <div class="table-responsive">             
              <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>País</th>
                  <th>Tasa</th>
                  <th>Fecha</th>
                  <th></th>
                  <% if current_user.type_person == 'admin' %>
                    <th></th>
                    <th></th>
                  <%end%>
                </tr>
              </thead>
              <tbody>
                <% @rates.each do |rate| %>
                  <tr>
                    <td><%= rate.country %></td>
                    <td><%= rate.value %></td>
                    <td><%= rate.updated_at.strftime("%d-%m-%Y %T") %></td>
                    <td><%= link_to 'MOSTRAR', rate, class:'waves-effect waves-light btn btn-theme' %></td>
                    <% if current_user.type_person == 'admin' %>
                      <td><%= link_to 'MODIFICAR', edit_rate_path(rate), class:'waves-effect waves-light btn btn-theme' %></td>
                      <td><%= link_to 'ELIMINAR',rate, method: :delete, data: { confirm: '¿Seguro que desea eliminar el país?' }, class:'waves-effect waves-light btn btn-theme' %></td>
                    <%end%>
                  </tr>
                <%end%>
              </tbody>
            </table>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
 

app/views/rates/new.html.erb
<div class="testing">
	<div class="wrapper ">
    <%= render 'partials/sidebar', report: false, worker: false, bank: false, rate: true %>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper"></div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          <!-- your content here -->
          <div class="titleDashContent">
            <h2>Tasa<br>
            <div class="line"></div></h2>
          </div>
          <div class="Dashcontent">
            <%= form_with(model: @rate, local: true) do |form| %>
              <% if @rate.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@rate.errors.count, "error") %> Se ha prohibido la creación de la tasa por:</h2>
                  <ul>
                    <% @rate.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="row">
                <div class="input-field col s12 l6">
                  <p>País</p>
                  <%= form.text_field :country, id: 'first_name', class: 'validate' %>
                </div>
                <div class="input-field col s12 l6">
                  <p>Valor</p>
                  <%= form.text_field :value, id: 'first_name', class: 'validate' %>
                </div>
              </div>
              <div class="input-field col s12">
                <%= link_to 'VOLVER', rates_path, class: "waves-effect waves-light btn btn-theme" %>
                <%= form.submit 'CREAR', class: "waves-effect waves-light btn btn-theme" %>
              </div>
            <% end %>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rates/show.html.erb
<div class="testing">
	<div class="wrapper ">
    <%= render 'partials/sidebar', report: false, worker: false, bank: false, rate: true %>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper"></div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          <p id="notice"><%= notice %></p>
          <!-- your content here -->
          <div class="titleDashContent">
            <h2>
              Tasa <br>
              <div class="line"></div>
            </h2>
          </div>
          <div class="Dashcontent">
            <div class="row">
              <div class="input-field col s12 l6">
                <p>País</p>
                <input id="first_name" type="text" class="validate" value="<%= @rate.country %>" disabled>
              </div>
              <div class="input-field col s12 l6">
                <p>Valor</p>
                <input id="first_name" type="text" class="validate" value="<%= @rate.value %>" disabled>
              </div>
            </div>
            <div class="input-field col s12">
              <%= link_to 'VOLVER', rates_path, class:"waves-effect waves-light btn btn-theme" %>
              <% if current_user.type_person == 'admin' %>
                <%= link_to 'EDITAR', edit_rate_path(@rate), class:"waves-effect waves-light btn btn-theme" %>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>